version: '3.8'
services:
  nest:
    container_name: nest
    build: .
    environment:
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    restart: always
    networks:
      - my-net

  postgres:
    container_name: postgres
    build: ./db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - my-net

volumes:
  postgres:

networks:
  my-net:
    driver: bridge