version: '3.8'
services:
  nest:
    container_name: nest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
    depends_on:
      - postgres-db
    restart: always
    networks:
      - app-net
    command: npm run start:dev

  postgres-db:
    container_name: postgres
    build:
      context: .
      dockerfile: ./db/Dockerfile
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - app-net

volumes:
  postgres:

networks:
  app-net:
    driver: bridge